name: "[Feature] Unity Actions 😎"

on: 
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    env:
      projectPath: src/
      unityVersion: 2021.3.16f1
      targetPlatform: Android # Build an Android player.
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0
          lfs: true

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3.2.2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v3.2.2
        with:
          path: ${{ env.projectPath }}/Library
          key:
            Library-${{ env.projectPath }}-${{ env.targetPlatform }}-${{
            hashFiles(env.projectPath) }}
          restore-keys: |
            Library-${{ env.projectPath }}-${{ env.targetPlatform }}-
            Library-${{ env.projectPath }}-
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2.1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.projectPath }}
          unityVersion: ${{ env.unityVersion }}
          targetPlatform: ${{ env.targetPlatform }}
          allowDirtyBuild: true
          versioning: Semantic
          androidAppBundle: false
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }} 
  
  pullToDevelop:
    name: Create pull request to develop
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0
          lfs: true

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3.2.2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Create pull request
      - name: Created pull request to develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "Pull ${{ github.ref }} into develop"
  
          

      

