name: "[Feature] Unity Actions 😎"

on: 
  push:
    branches:
      - 'feature/**'

jobs:
  pullToDevelop:
    name: Create pull request to develop
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0
          lfs: true

      # Create pull request
      - name: Created pull request to develop
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ github.ref_name }}
          base: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto PR ${{ github.ref_name }}  to develop'

